export * from './about/about.component';
export * from './contact/contact.component';
export * from './footer/footer.component';
export * from './icon/icon.component';
export * from './navbar/navbar.component';
export * from './projects/projects.component';
export * from './resume/resume.component';
export * from './section-header/section-header.component';
export * from './slider/slider.component';
